# Use the official Python base image for Raspberry Pi OS
FROM arm32v7/python:3.9-slim-buster

# Set the working directory inside the container
WORKDIR /app

# Install necessary dependencies
# RUN sudo apt-get install -y python3-rpi.gpio
# RUN apt-get install -y xterm

# Enable I2C in config.txt
RUN echo "dtparam=i2c_arm=on" >> /boot/config.txt

# Copy the Python script and other necessary files to the working directory
COPY FabFivePi.py .
COPY startup_script.sh .

# Grant execute permissions to the startup script
RUN chmod +x startup_script.sh

# Install any necessary Python dependencies
RUN pip install RPLCD

# Copy the modified entrypoint script
COPY /entrypoint.sh /entrypoint.sh

# Grant execute permissions to the entrypoint script
RUN chmod +x /entrypoint.sh

# Set the entrypoint command to run the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]
