-- SQLite

CREATE DATABASE  IF NOT EXISTS Fablab;
USE Fablab;
CREATE TABLE IF NOT EXISTS USERS (
userID INTEGER NOT NULL PRIMARY KEY,
AdminStatus INTEGER NOT NULL, 
MachineType TEXT NOT NULL, 
Date TEXT NOT NULL, 
StartTime TEXT NOT NULL,
EndTime TEXT NOT NULL);


